/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-julia_mod
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_JULIA_MOD_API_H
#define INCLUDED_JULIA_MOD_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_julia_mod_EXPORTS
#define JULIA_MOD_API __GR_ATTR_EXPORT
#else
#define JULIA_MOD_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_JULIA_MOD_API_H */
